# Site settings
title: Akansha Vashisth
description: A blog about Computer science
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

username: Akansha Vashisth
user_description: My journey in Computer Science Engineering
user_subtitle: Engineering and Data Science
email: akanshavashisth@gmail.com
linkedin_username: akanshavashisth
instagram_username: akavashisth
twitter_username: vashisth_ak
github_username:  akanshaVashisth

sass:
  sass_dir: css
  style: compressed
